interface SiteFormConfigType {
  SITES_SETTING_FORM_ID_CREATE_SITE: string;
  SITES_SETTING_FORM_ID_GENERALE: string;
  SITES_SETTING_FORM_ID_SETUP_GUIDE: string;
  SITES_SETTING_FORM_ID_PLAN: string;
  SITES_SETTING_FORM_ID_BILLING: string;
  SITES_SETTING_FORM_ID_USERS_PERMISSIONS: string;
  SITES_SETTING_FORM_ID_PAYMENTS: string;
  SITES_SETTING_FORM_ID_CHECKOUT: string;
  SITES_SETTING_FORM_ID_CUSTOMER_ACCOUNTS: string;
  SITES_SETTING_FORM_ID_SHIPPING: string;
  SITES_SETTING_FORM_ID_TAXES: string;
  SITES_SETTING_FORM_ID_LOCATIONS: string;
  SITES_SETTING_FORM_ID_MARKETS: string;
  SITES_SETTING_FORM_ID_APPS_SALES_CHANNELS: string;
  SITES_SETTING_FORM_ID_DOMAINS: string;
  SITES_SETTING_FORM_ID_CUSTOMER_EVENTS: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS_STAFF: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS_WEBHOOK: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS_CUSTOMER: string;
  SITES_SETTING_FORM_ID_CUSTOM_DATA: string;
  SITES_SETTING_FORM_ID_LANGUAGES_DATA: string;
  SITES_SETTING_FORM_ID_PRIVACY_DATA: string;
  SITES_SETTING_FORM_ID_POLICY_DATA: string;
  SITES_SETTING_FORM_ID_LOCATION_DETAILS: string;
  SITES_SETTING_FORM_ID_SHIPPING_PROFILES: string;
  SITES_SETTING_FORM_ID_SHIPPING_ZONES: string;
  SITES_SETTING_FORM_ID_MARKETS_RULES: string;
  SITES_SETTING_FORM_ID_SHIPPING_LOCATIONS: string;
  SITES_SETTING_FORM_ID_TAXES_REGIONAL: string;

  SITES_FORM_ID_CONTENT_FILE: string;
  SITES_FORM_ID_CONTENT_META_OBJECTS: string;
  SITES_FORM_ID_CUSTOMER: string;
  SITES_FORM_ID_CUSTOMER_SEGMENTS: string;
  SITES_FORM_ID_DEMO_PREVIEW: string;
  SITES_FORM_ID_DISCOUNTS: string;
  SITES_FORM_ID_ONLINE_STORE_MENU: string;
  SITES_FORM_ID_ONLINE_STORE_PAGE: string;
  SITES_FORM_ID_ONLINE_STORE_POST: string;
  SITES_FORM_ID_ONLINE_STORE_PREFERENCES: string;
  SITES_FORM_ID_ORDER: string;
  SITES_FORM_ID_ORDER_CHECKOUTS: string;
  SITES_FORM_ID_ORDER_DRAFT: string;
  SITES_FORM_ID_PRODUCT: string;
  SITES_FORM_ID_PRODUCT_COLLECTIONS: string;
  SITES_FORM_ID_PRODUCT_GIFT: string;
  SITES_FORM_ID_PRODUCT_INVENTORY: string;
  SITES_FORM_ID_PRODUCT_PURCHASE: string;
  SITES_FORM_ID_PRODUCT_TRANSFERS: string;
  SITES_FORM_ID_PRODUCT_VARIANTS: string;
  SITES_FORM_ID_ONLINE_STORE_BLOG: string;
  //   [key: string]: string;
}

const SiteFormConfig: SiteFormConfigType = {
  SITES_SETTING_FORM_ID_CREATE_SITE: "SITES_SETTING_FORM_ID_CREATE_SITE",
  SITES_SETTING_FORM_ID_GENERALE: "SITES_SETTING_FORM_ID_GENERALE",
  SITES_SETTING_FORM_ID_SETUP_GUIDE: "SITES_SETTING_FORM_ID_SETUP_GUIDE",
  SITES_SETTING_FORM_ID_PLAN: "SITES_SETTING_FORM_ID_PLAN",
  SITES_SETTING_FORM_ID_BILLING: "SITES_SETTING_FORM_ID_BILLING",
  SITES_SETTING_FORM_ID_USERS_PERMISSIONS:
    "SITES_SETTING_FORM_ID_USERS_PERMISSIONS",
  SITES_SETTING_FORM_ID_PAYMENTS: "SITES_SETTING_FORM_ID_PAYMENTS",
  SITES_SETTING_FORM_ID_CHECKOUT: "SITES_SETTING_FORM_ID_CHECKOUT",
  SITES_SETTING_FORM_ID_CUSTOMER_ACCOUNTS:
    "SITES_SETTING_FORM_ID_CUSTOMER_ACCOUNTS",
  SITES_SETTING_FORM_ID_SHIPPING: "SITES_SETTING_FORM_ID_SHIPPING",
  SITES_SETTING_FORM_ID_TAXES: "SITES_SETTING_FORM_ID_TAXES",
  SITES_SETTING_FORM_ID_LOCATIONS: "SITES_SETTING_FORM_ID_LOCATIONS",
  SITES_SETTING_FORM_ID_MARKETS: "SITES_SETTING_FORM_ID_MARKETS",
  SITES_SETTING_FORM_ID_APPS_SALES_CHANNELS:
    "SITES_SETTING_FORM_ID_APPS_SALES_CHANNELS",
  SITES_SETTING_FORM_ID_DOMAINS: "SITES_SETTING_FORM_ID_DOMAINS",
  SITES_SETTING_FORM_ID_CUSTOMER_EVENTS:
    "SITES_SETTING_FORM_ID_CUSTOMER_EVENTS",
  SITES_SETTING_FORM_ID_NOTIFICATIONS: "SITES_SETTING_FORM_ID_NOTIFICATIONS",
  SITES_SETTING_FORM_ID_NOTIFICATIONS_STAFF:
    "SITES_SETTING_FORM_ID_NOTIFICATIONS_STAFF",
  SITES_SETTING_FORM_ID_NOTIFICATIONS_WEBHOOK:
    "SITES_SETTING_FORM_ID_NOTIFICATIONS_WEBHOOK",
  SITES_SETTING_FORM_ID_NOTIFICATIONS_CUSTOMER:
    "SITES_SETTING_FORM_ID_NOTIFICATIONS_CUSTOMER",
  SITES_SETTING_FORM_ID_CUSTOM_DATA: "SITES_SETTING_FORM_ID_CUSTOM_DATA",
  SITES_SETTING_FORM_ID_LANGUAGES_DATA: "SITES_SETTING_FORM_ID_LANGUAGES_DATA",
  SITES_SETTING_FORM_ID_PRIVACY_DATA: "SITES_SETTING_FORM_ID_PRIVACY_DATA",
  SITES_SETTING_FORM_ID_POLICY_DATA: "SITES_SETTING_FORM_ID_POLICY_DATA",
  SITES_SETTING_FORM_ID_LOCATION_DETAILS:
    "SITES_SETTING_FORM_ID_LOCATION_DETAILS",
  SITES_SETTING_FORM_ID_SHIPPING_PROFILES:
    "SITES_SETTING_FORM_ID_SHIPPING_PROFILES",
  SITES_SETTING_FORM_ID_SHIPPING_ZONES: "SITES_SETTING_FORM_ID_SHIPPING_ZONES",
  SITES_SETTING_FORM_ID_MARKETS_RULES: "SITES_SETTING_FORM_ID_MARKETS_RULES",
  SITES_SETTING_FORM_ID_SHIPPING_LOCATIONS:
    "SITES_SETTING_FORM_ID_SHIPPING_LOCATIONS",
  SITES_SETTING_FORM_ID_TAXES_REGIONAL: "SITES_SETTING_FORM_ID_TAXES_REGIONAL",

  SITES_FORM_ID_CONTENT_FILE: "SITES_FORM_ID_CONTENT_FILE",
  SITES_FORM_ID_CONTENT_META_OBJECTS: "SITES_FORM_ID_CONTENT_META_OBJECTS",
  SITES_FORM_ID_CUSTOMER: "SITES_FORM_ID_CUSTOMER",
  SITES_FORM_ID_CUSTOMER_SEGMENTS: "SITES_FORM_ID_CUSTOMER_SEGMENTS",
  SITES_FORM_ID_DEMO_PREVIEW: "SITES_FORM_ID_DEMO_PREVIEW",
  SITES_FORM_ID_DISCOUNTS: "SITES_FORM_ID_DISCOUNTS",
  SITES_FORM_ID_ONLINE_STORE_MENU: "SITES_FORM_ID_ONLINE_STORE_MENU",
  SITES_FORM_ID_ONLINE_STORE_PAGE: "SITES_FORM_ID_ONLINE_STORE_PAGE",
  SITES_FORM_ID_ONLINE_STORE_POST: "SITES_FORM_ID_ONLINE_STORE_POST",
  SITES_FORM_ID_ONLINE_STORE_PREFERENCES:
    "SITES_FORM_ID_ONLINE_STORE_PREFERENCES",
  SITES_FORM_ID_ORDER: "SITES_FORM_ID_ORDER",
  SITES_FORM_ID_ORDER_CHECKOUTS: "SITES_FORM_ID_ORDER_CHECKOUTS",
  SITES_FORM_ID_ORDER_DRAFT: "SITES_FORM_ID_ORDER_DRAFT",
  SITES_FORM_ID_PRODUCT: "SITES_FORM_ID_PRODUCT",
  SITES_FORM_ID_PRODUCT_COLLECTIONS: "SITES_FORM_ID_PRODUCT_COLLECTIONS",
  SITES_FORM_ID_PRODUCT_GIFT: "SITES_FORM_ID_PRODUCT_GIFT",
  SITES_FORM_ID_PRODUCT_INVENTORY: "SITES_FORM_ID_PRODUCT_INVENTORY",
  SITES_FORM_ID_PRODUCT_PURCHASE: "SITES_FORM_ID_PRODUCT_PURCHASE",
  SITES_FORM_ID_PRODUCT_TRANSFERS: "SITES_FORM_ID_PRODUCT_TRANSFERS",
  SITES_FORM_ID_PRODUCT_VARIANTS: "SITES_FORM_ID_PRODUCT_VARIANTS",
  SITES_FORM_ID_ONLINE_STORE_BLOG: "SITES_FORM_ID_ONLINE_STORE_BLOG",
};

export default SiteFormConfig;
