interface SiteFormConfigType {
  SITES_SETTING_FORM_ID_CREATE_SITE: string;
  SITES_SETTING_FORM_ID_GENERALE: string;
  SITES_SETTING_FORM_ID_SETUP_GUIDE: string;
  SITES_SETTING_FORM_ID_PLAN: string;
  SITES_SETTING_FORM_ID_BILLING: string;
  SITES_SETTING_FORM_ID_USERS_PERMISSIONS: string;
  SITES_SETTING_FORM_ID_PAYMENTS: string;
  SITES_SETTING_FORM_ID_CHECKOUT: string;
  SITES_SETTING_FORM_ID_CUSTOMER_ACCOUNTS: string;
  SITES_SETTING_FORM_ID_SHIPPING: string;
  SITES_SETTING_FORM_ID_TAXES: string;
  SITES_SETTING_FORM_ID_LOCATIONS: string;
  SITES_SETTING_FORM_ID_MARKETS: string;
  SITES_SETTING_FORM_ID_APPS_SALES_CHANNELS: string;
  SITES_SETTING_FORM_ID_DOMAINS: string;
  SITES_SETTING_FORM_ID_CUSTOMER_EVENTS: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS_STAFF: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS_WEBHOOK: string;
  SITES_SETTING_FORM_ID_NOTIFICATIONS_CUSTOMER: string;
  SITES_SETTING_FORM_ID_CUSTOM_DATA: string;
  SITES_SETTING_FORM_ID_LANGUAGES_DATA: string;
  SITES_SETTING_FORM_ID_PRIVACY_DATA: string;
  SITES_SETTING_FORM_ID_POLICY_DATA: string;
  //   [key: string]: string;
}

const SiteFormConfig: SiteFormConfigType = {
  SITES_SETTING_FORM_ID_CREATE_SITE: "SITES_SETTING_FORM_ID_CREATE_SITE",
  SITES_SETTING_FORM_ID_GENERALE: "SITES_SETTING_FORM_ID_GENERALE",
  SITES_SETTING_FORM_ID_SETUP_GUIDE: "SITES_SETTING_FORM_ID_SETUP_GUIDE",
  SITES_SETTING_FORM_ID_PLAN: "SITES_SETTING_FORM_ID_PLAN",
  SITES_SETTING_FORM_ID_BILLING: "SITES_SETTING_FORM_ID_BILLING",
  SITES_SETTING_FORM_ID_USERS_PERMISSIONS:
    "SITES_SETTING_FORM_ID_USERS_PERMISSIONS",
  SITES_SETTING_FORM_ID_PAYMENTS: "SITES_SETTING_FORM_ID_PAYMENTS",
  SITES_SETTING_FORM_ID_CHECKOUT: "SITES_SETTING_FORM_ID_CHECKOUT",
  SITES_SETTING_FORM_ID_CUSTOMER_ACCOUNTS:
    "SITES_SETTING_FORM_ID_CUSTOMER_ACCOUNTS",
  SITES_SETTING_FORM_ID_SHIPPING: "SITES_SETTING_FORM_ID_SHIPPING",
  SITES_SETTING_FORM_ID_TAXES: "SITES_SETTING_FORM_ID_TAXES",
  SITES_SETTING_FORM_ID_LOCATIONS: "SITES_SETTING_FORM_ID_LOCATIONS",
  SITES_SETTING_FORM_ID_MARKETS: "SITES_SETTING_FORM_ID_MARKETS",
  SITES_SETTING_FORM_ID_APPS_SALES_CHANNELS:
    "SITES_SETTING_FORM_ID_APPS_SALES_CHANNELS",
  SITES_SETTING_FORM_ID_DOMAINS: "SITES_SETTING_FORM_ID_DOMAINS",
  SITES_SETTING_FORM_ID_CUSTOMER_EVENTS:
    "SITES_SETTING_FORM_ID_CUSTOMER_EVENTS",
  SITES_SETTING_FORM_ID_NOTIFICATIONS: "SITES_SETTING_FORM_ID_NOTIFICATIONS",
  SITES_SETTING_FORM_ID_NOTIFICATIONS_STAFF:
    "SITES_SETTING_FORM_ID_NOTIFICATIONS_STAFF",
  SITES_SETTING_FORM_ID_NOTIFICATIONS_WEBHOOK:
    "SITES_SETTING_FORM_ID_NOTIFICATIONS_WEBHOOK",
  SITES_SETTING_FORM_ID_NOTIFICATIONS_CUSTOMER:
    "SITES_SETTING_FORM_ID_NOTIFICATIONS_CUSTOMER",
  SITES_SETTING_FORM_ID_CUSTOM_DATA: "SITES_SETTING_FORM_ID_CUSTOM_DATA",
  SITES_SETTING_FORM_ID_LANGUAGES_DATA: "SITES_SETTING_FORM_ID_LANGUAGES_DATA",
  SITES_SETTING_FORM_ID_PRIVACY_DATA: "SITES_SETTING_FORM_ID_PRIVACY_DATA",
  SITES_SETTING_FORM_ID_POLICY_DATA: "SITES_SETTING_FORM_ID_POLICY_DATA",
};

export default SiteFormConfig;
